---
title: Publications
---

<!-- After the .bib file is updated, knit this Rmd to update publications.html, then commit and push both the .bib and .html -->

[Google Scholar curated citations](https://scholar.google.com/citations?user=P5Rt1VEAAAAJ&hl=en)

[Download BibTeX file](https://keaven.github.io/keaven.bib)

```{r, include=FALSE}
df <- bib2df::bib2df("keaven.bib") |> suppressWarnings()
df <- df[order(df$YEAR, decreasing = TRUE), ]

# Copy the assets into a temporary directory to render
create_tempdir <- function(name) {
  path <- file.path(tempdir(), name)
  if (dir.exists(path)) unlink(path, recursive = TRUE)
  dir.create(path)
  invisible(path)
}

path_dir <- create_tempdir("pub")
path_rmd <- file.path(path_dir, "pub.Rmd")
path_md <- file.path(path_dir, "pub.md")
file.copy(from = "keaven.bib", to = path_dir, overwrite = TRUE) |> invisible()
file.copy(from = "apa-numeric-superscript-brackets.csl", to = path_dir, overwrite = TRUE) |> invisible()

c(
  "---",
  "output: md_document",
  "bibliography: keaven.bib",
  "csl: apa-numeric-superscript-brackets.csl",
  "---",
  "",
  paste0("@", df$BIBTEXKEY)
) |>
  writeLines(con = path_rmd)

withr::with_dir(
  path_dir,
  rmarkdown::render(path_rmd, output_file = path_md)
)

# Remove the reference anchors
md_text <- path_md |>
  readLines() |>
  gsub("^<sup>.*</sup>", "", x = _) |>
  gsub("^\\d+\\\\\\.\\s", "- ", x = _)

# Remove the remaining blank lines at top
md_text <- md_text[-(1L:(which(md_text != "")[1] - 2L))]

# Tag the first article of that year with year headings
idx_year <- which(md_text == "")
v <- cumsum(rle(df$YEAR)$lengths) + 1L
idx_first_year <- c(1L, v[-length(v)])
md_text[idx_year[idx_first_year]] <- paste0("## ", df$YEAR[idx_first_year])

# Add blank line around year headings
# <https://stackoverflow.com/a/18951302>
insert_at <- function(x, pos, lst) {
  stopifnot(length(lst) == length(pos))
  res <- vector("list", 2 * length(pos) + 1)
  res[c(TRUE, FALSE)] <- split(x, cumsum(seq_along(x) %in% (pos + 1)))
  res[c(FALSE, TRUE)] <- lst
  unlist(res)
}

md_text <- md_text |>
  insert_at(
    c(idx_year[idx_first_year] - 1L, idx_year[idx_first_year])[-1],
    as.list(rep("", length(idx_first_year) * 2 - 1))
  )
```

```{r, echo=FALSE, results="asis"}
cat(paste0(md_text, collapse = "\n"))
```
